name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore src/GenerateInterface.sln
    
    - name: Build
      run: dotnet build src/GenerateInterface.sln --configuration Release --no-restore
    
    - name: Test example project
      run: dotnet run --project src/GenerateInterface.Example --configuration Release --no-build