name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore src/GenerateInterface.sln
    
    - name: Build
      run: dotnet build src/GenerateInterface.sln --configuration Release --no-restore
    
    - name: Test example project
      run: dotnet run --project src/GenerateInterface.Example --configuration Release --no-build
    
    - name: Verify generated interfaces exist
      run: |
        # List all generated files to debug
        echo "Looking for generated files:"
        find src/GenerateInterface.Example/obj -name "*.cs" -type f | grep -v GlobalUsings | grep -v AssemblyInfo | grep -v AssemblyAttributes
        
        # Check if any interface files were generated (more flexible pattern)
        if find src/GenerateInterface.Example/obj -name "*Interface*.g.cs" -type f | grep -q .; then
          echo "Source generator successfully generated interface files"
        else
          echo "No interface files were generated by source generator"
          echo "Checking compilation output for errors..."
          exit 1
        fi
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package
        path: src/GenerateInterface/bin/Release/*.nupkg